name: Single compatibility job

on:
  workflow_call:
    inputs:
      rebar_version:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  SETUP_BEAM_2:        /home/runner/work/_temp/.setup-beam-2
  HORUS_TEST_EXECUTOR: /home/runner/work/_temp/.setup-beam-2/otp/bin/erl

jobs:
  test:
    name: "Erlang/OTP ${{ matrix.from_otp_version }} -> ${{ matrix.to_otp_version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        from_otp_version: ['26', '27', '28', '29']
        to_otp_version:   ['26', '27', '28', '29']
        exclude:
          - { from_otp_version: '26', to_otp_version: '26' }
          - { from_otp_version: '27', to_otp_version: '27' }
          - { from_otp_version: '28', to_otp_version: '28' }
          - { from_otp_version: '29', to_otp_version: '29' }

    steps:
      - uses: actions/checkout@v6

      - name: Install Erlang/OTP ${{ matrix.to_otp_version }} ("to")
        uses: erlef/setup-beam@v1
        id: install-erlang-2
        with:
          otp-version: ${{ matrix.to_otp_version }}
          rebar3-version: ${{ inputs.rebar_version }}

      - name: Prepare workspace for second Erlang/OTP install
        run: |
          mv ~/work/_temp/.setup-beam "$SETUP_BEAM_2"
          sed -E -i'' -e 's|.setup-beam/otp|.setup-beam2/otp|' $HORUS_TEST_EXECUTOR

      - name: Install Erlang/OTP ${{ matrix.from_otp_version }} ("from")
        uses: erlef/setup-beam@v1
        id: install-erlang-1
        with:
          otp-version: ${{ matrix.from_otp_version }}
          rebar3-version: ${{ inputs.rebar_version }}

      - name: Ensure second Erlang/OTP version differs from first
        run: |
          set -x
          which erl
          erl -noinput -eval 'io:format("~s~n", [erlang:system_info(otp_release)]), halt().' > erlang-version-1.txt
          $HORUS_TEST_EXECUTOR -noinput -eval 'io:format("~s~n", [erlang:system_info(otp_release)]), halt().' > erlang-version-2.txt
          ! diff -u erlang-version-1.txt erlang-version-2.txt
          ! cmp -s erlang-version-1.txt erlang-version-2.txt

      - name: Compile
        run: rebar3 compile

      - name: EUnit (unit tests)
        run: |
          export ERL_FLAGS='-enable-feature maybe_expr'
          rebar3 eunit --verbose
