name: Documentation

on:
  push:
    branches:
      - 'main'

jobs:
  Documentation:
    name: Generate and publish documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          rebar3-version: '3.23.0'

      - name: Change doc version to "Development branch"
        run: sed -E -i -e 's/^@version.*/@version Development branch/' doc/overview.edoc

      - name: Generate
        run: rebar3 edoc

      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
